export const homeData = {
    "movies": [
      {
        "id": 1,
        "title": "Drama",
        "movies": [
          {
            id: 1,
            title: 'The Shawshank Redemption',
            year: 1994,
            genre: 'Drama',
            description: 'Two imprisoned men bond over years, finding solace and redemption through acts of decency.',
            director: 'Frank Darabont',
            cast: ['John Doe', 'Jane Smith', 'Mike Lee'],
            runtime_minutes: 142,
            rating: 'R',
            imdb_score: 9.3,
            budget_usd: 25000000,
            box_office_usd: 58800000,
            synopsis: 'Andy Dufresne, wrongly convicted, plans his escape from prison.',
            banner_image: 'https://image.tmdb.org/t/p/original/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg',
            thumbnail_image: 'https://image.tmdb.org/t/p/w1280/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg',
            video_link: 'https://www.youtube.com/embed/6hB3S9bIaco'
          },
          {
            id: 6,
            title: 'Forrest Gump',
            year: 1994,
            genre: 'Drama',
            description: 'A man with a low IQ experiences key events in American history.',
            director: 'Robert Zemeckis',
            cast: ['John Doe', 'Jane Smith', 'Mike Lee'],
            runtime_minutes: 142,
            rating: 'PG-13',
            imdb_score: 8.8,
            budget_usd: 55000000,
            box_office_usd: 677000000,
            synopsis: 'Forrest unwittingly influences decades of history.',
            banner_image: 'https://image.tmdb.org/t/p/original/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg',
            thumbnail_image: 'https://image.tmdb.org/t/p/w1280/saHP97rXYCB3L0MKdWPuTO5M092.jpg',
            video_link: 'https://www.youtube.com/embed/bLvqoHBptjg'
          },
          {
            id: 13,
            title: 'Fight Club',
            year: 1999,
            genre: 'Drama',
            description: 'An insomniac forms an underground fight club.',
            director: 'David Fincher',
            cast: ['John Doe', 'Jane Smith', 'Mike Lee'],
            runtime_minutes: 139,
            rating: 'R',
            imdb_score: 8.8,
            budget_usd: 63000000,
            box_office_usd: 101000000,
            synopsis: 'A man creates chaos through an alter ego.',
            banner_image: 'https://image.tmdb.org/t/p/original/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg',
            thumbnail_image: 'https://image.tmdb.org/t/p/w1280/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg',
            video_link: 'https://www.youtube.com/embed/SUXWAEX2jlg'
          },
          {
            id: 15,
            title: 'Good Will Hunting',
            year: 1997,
            genre: 'Drama',
            description: 'A genius janitor finds purpose through therapy.',
            director: 'Gus Van Sant',
            cast: ['John Doe', 'Jane Smith', 'Mike Lee'],
            runtime_minutes: 126,
            rating: 'R',
            imdb_score: 8.3,
            budget_usd: 10000000,
            box_office_usd: 225000000,
            synopsis: 'Will Hunting finds his path with help.',
            banner_image: 'https://image.tmdb.org/t/p/original/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg',
            thumbnail_image: 'https://image.tmdb.org/t/p/w1280/bABCBZY6TJ2R9Y97C6fUOZrh2Xs.jpg',
            video_link: 'https://www.youtube.com/embed/PaZVjZEFkRs'
          },
          {
            id: 23,
            title: 'The Green Mile',
            year: 1999,
            genre: 'Drama',
            description: 'A death row guard encounters a special inmate.',
            director: 'Frank Darabont',
            cast: ['John Doe', 'Jane Smith', 'Mike Lee'],
            runtime_minutes: 189,
            rating: 'R',
            imdb_score: 8.6,
            budget_usd: 60000000,
            box_office_usd: 286000000,
            synopsis: "A guard discovers an inmate's miraculous gift.",
            banner_image: 'https://image.tmdb.org/t/p/original/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg',
            thumbnail_image: 'https://image.tmdb.org/t/p/w1280/velW2eNCSnXefoQpj7ztEFVS5.jpg',
            video_link: 'https://www.youtube.com/embed/Ki4haFrqSrw'
          },
          {
            id: 40,
            title: 'Whiplash',
            year: 2014,
            genre: 'Drama',
            description: 'A drummer faces an intense music instructor.',
            director: 'Damien Chazelle',
            cast: ['John Doe', 'Jane Smith', 'Mike Lee'],
            runtime_minutes: 107,
            rating: 'R',
            imdb_score: 8.5,
            budget_usd: 3300000,
            box_office_usd: 49000000,
            synopsis: 'A drummer endures a harsh teacher.',
            banner_image: 'https://image.tmdb.org/t/p/original/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg',
            thumbnail_image: 'https://image.tmdb.org/t/p/w1280/6uSPcdGNAHrWHs3gWg3S3kD5M5p.jpg',
            video_link: 'https://www.youtube.com/embed/7d_jQihdBng'
          }
        ]
      },
      {
        "id": 2,
        "title": "Crime",
        "movies": [
          {
            id: 2,
            title: 'The Godfather',
            year: 1972,
            genre: 'Crime',
            description: 'The aging patriarch of an organized crime dynasty transfers control to his reluctant son.',
            director: 'Francis Ford Coppola',
            cast: ['John Doe', 'Jane Smith', 'Mike Lee'],
            runtime_minutes: 175,
            rating: 'R',
            imdb_score: 9.2,
            budget_usd: 6000000,
            box_office_usd: 245000000,
            synopsis: 'Michael Corleone takes over the family mafia business.',
            banner_image: 'https://image.tmdb.org/t/p/original/3bhkrj58Vtu7enYsRolD1fZdja1.jpg',
            thumbnail_image: 'https://image.tmdb.org/t/p/w1280/3bhkrj58Vtu7enYsRolD1fZdja1.jpg',
            video_link: 'https://www.youtube.com/embed/sY1S34973zA'
          },
          {
            id: 4,
            title: 'Pulp Fiction',
            year: 1994,
            genre: 'Crime',
            description: 'Various interconnected stories of criminals, hitmen, and a mysterious briefcase.',
            director: 'Quentin Tarantino',
            cast: ['John Doe', 'Jane Smith', 'Mike Lee'],
            runtime_minutes: 154,
            rating: 'R',
            imdb_score: 8.9,
            budget_usd: 8000000,
            box_office_usd: 213000000,
            synopsis: 'Intertwined tales of violence and redemption.',
            banner_image: 'https://image.tmdb.org/t/p/original/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg',
            thumbnail_image: 'https://image.tmdb.org/t/p/w1280/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg',
            video_link: 'https://www.youtube.com/embed/s7EdQ4FqbhY'
          },
          {
            id: 20,
            title: 'The Departed',
            year: 2006,
            genre: 'Crime',
            description: 'An undercover cop and a mole collide in Boston.',
            director: 'Martin Scorsese',
            cast: ['John Doe', 'Jane Smith', 'Mike Lee'],
            runtime_minutes: 151,
            rating: 'R',
            imdb_score: 8.5,
            budget_usd: 90000000,
            box_office_usd: 291000000,
            synopsis: "A cop and a mole infiltrate each other's worlds.",
            banner_image: 'https://image.tmdb.org/t/p/original/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg',
            thumbnail_image: 'https://image.tmdb.org/t/p/w1280/nT97ifVTwfA5XncTs3X7wlauJPG.jpg',
            video_link: 'https://www.youtube.com/embed/SGWvwjZ0eDo'
          },
          {
            id: 8,
            title: 'The Dark Knight',
            year: 2008,
            genre: 'Crime',
            description: "Batman faces the Joker in a battle for Gotham's soul.",
            director: 'Christopher Nolan',
            cast: ['John Doe', 'Jane Smith', 'Mike Lee'],
            runtime_minutes: 152,
            rating: 'PG-13',
            imdb_score: 9,
            budget_usd: 185000000,
            box_office_usd: 1004000000,
            synopsis: 'Batman battles the chaotic Joker.',
            banner_image: 'https://image.tmdb.org/t/p/original/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
            thumbnail_image: 'https://image.tmdb.org/t/p/w1280/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
            video_link: 'https://www.youtube.com/embed/EXeTwQWrcwY'
          },
        ]
      },
      {
        "id": 3,
        "title":  "Sci-Fi",
        "movies": [
          {
            id: 3,
            title: 'Inception',
            year: 2010,
            genre: 'Sci-Fi',
            description: 'A thief with the ability to enter dreams is given a final job that could win him his freedom.',
            director: 'Christopher Nolan',
            cast: ['John Doe', 'Jane Smith', 'Mike Lee'],
            runtime_minutes: 148,
            rating: 'PG-13',
            imdb_score: 8.8,
            budget_usd: 160000000,
            box_office_usd: 829000000,
            synopsis: 'Dom Cobb plants an idea in a dream within a dream.',
            banner_image: 'https://image.tmdb.org/t/p/original/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg',
            thumbnail_image: 'https://image.tmdb.org/t/p/w1280/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg',
            video_link: 'https://www.youtube.com/embed/YoHD9XEInc0'
          },
          {
            id: 5,
            title: 'The Matrix',
            year: 1999,
            genre: 'Sci-Fi',
            description: 'A computer hacker learns about the true nature of reality and his role in the war against its controllers.',
            director: 'The Wachowskis',
            cast: ['John Doe', 'Jane Smith', 'Mike Lee'],
            runtime_minutes: 136,
            rating: 'R',
            imdb_score: 8.7,
            budget_usd: 63000000,
            box_office_usd: 463000000,
            synopsis: 'Neo fights to free humanity from a simulation.',
            banner_image: 'https://image.tmdb.org/t/p/original/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg',
            thumbnail_image: 'https://image.tmdb.org/t/p/w1280/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg',
            video_link: 'https://www.youtube.com/embed/m8e-FF8MsqU'
          },
          {
            id: 10,
            title: 'Star Wars: Episode IV',
            year: 1977,
            genre: 'Sci-Fi',
            description: 'A young man joins rebels to fight an evil empire.',
            director: 'George Lucas',
            cast: ['John Doe', 'Jane Smith', 'Mike Lee'],
            runtime_minutes: 121,
            rating: 'PG',
            imdb_score: 8.6,
            budget_usd: 11000000,
            box_office_usd: 775000000,
            synopsis: 'Luke Skywalker joins the Rebel Alliance.',
            banner_image: 'https://image.tmdb.org/t/p/original/6FfCtAuVAW8XJjZ7eWeLibRLWTw.jpg',
            thumbnail_image: 'https://image.tmdb.org/t/p/w1280/6FfCtAuVAW8XJjZ7eWeLibRLWTw.jpg',
            video_link: 'https://www.youtube.com/embed/vZ734NWnAHA'
          },
          {
            id: 17,
            title: 'Avatar',
            year: 2009,
            genre: 'Sci-Fi',
            description: 'A marine connects with an alien world.',
            director: 'James Cameron',
            cast: ['John Doe', 'Jane Smith', 'Mike Lee'],
            runtime_minutes: 162,
            rating: 'PG-13',
            imdb_score: 7.9,
            budget_usd: 237000000,
            box_office_usd: 2789000000,
            synopsis: "Jake Sully bonds with Pandora's natives.",
            banner_image: 'https://image.tmdb.org/t/p/original/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg',
            thumbnail_image: 'https://image.tmdb.org/t/p/w1280/jRXYjXNq0Cs2TcJjLkkiOBpomox.jpg',
            video_link: 'https://www.youtube.com/embed/5PSNL1qE6VY'
          },
          {
            id: 21,
            title: 'Interstellar',
            year: 2014,
            genre: 'Sci-Fi',
            description: 'Astronauts seek a new home for humanity.',
            director: 'Christopher Nolan',
            cast: ['John Doe', 'Jane Smith', 'Mike Lee'],
            runtime_minutes: 169,
            rating: 'PG-13',
            imdb_score: 8.7,
            budget_usd: 165000000,
            box_office_usd: 701000000,
            synopsis: 'Cooper searches for a new Earth.',
            banner_image: 'https://image.tmdb.org/t/p/original/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg',
            thumbnail_image: 'https://image.tmdb.org/t/p/w1280/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
            video_link: 'https://www.youtube.com/embed/zSWdZVtXT7E'
          },
          {
            id: 22,
            title: 'The Empire Strikes Back',
            year: 1980,
            genre: 'Sci-Fi',
            description: "The rebels face Darth Vader's wrath.",
            director: 'Irvin Kershner',
            cast: ['John Doe', 'Jane Smith', 'Mike Lee'],
            runtime_minutes: 124,
            rating: 'PG',
            imdb_score: 8.7,
            budget_usd: 18000000,
            box_office_usd: 538000000,
            synopsis: 'Luke trains as a Jedi while facing Vader.',
            banner_image: 'https://image.tmdb.org/t/p/original/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg',
            thumbnail_image: 'https://image.tmdb.org/t/p/w1280/nNAeTmQdK2hL2HLCX1KFgCxK2rz.jpg',
            video_link: 'https://www.youtube.com/embed/JNwNXF9Y6kY'
          },
          {
            id: 29,
            title: 'Back to the Future',
            year: 1985,
            genre: 'Sci-Fi',
            description: "A teen time-travels to his parents' past.",
            director: 'Robert Zemeckis',
            cast: ['John Doe', 'Jane Smith', 'Mike Lee'],
            runtime_minutes: 116,
            rating: 'PG',
            imdb_score: 8.5,
            budget_usd: 19000000,
            box_office_usd: 381000000,
            synopsis: "Marty fixes his parents' past.",
            banner_image: 'https://image.tmdb.org/t/p/original/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg',
            thumbnail_image: 'https://image.tmdb.org/t/p/w1280/fNOH9fE4CkzD6kPLj0norOKmTob.jpg',
            video_link: 'https://www.youtube.com/embed/qvsgGtivCgs'
          },
          {
            id: 36,
            title: 'Blade Runner',
            year: 1982,
            genre: 'Sci-Fi',
            description: 'A detective hunts rogue androids in the future.',
            director: 'Ridley Scott',
            cast: ['John Doe', 'Jane Smith', 'Mike Lee'],
            runtime_minutes: 117,
            rating: 'R',
            imdb_score: 8.1,
            budget_usd: 28000000,
            box_office_usd: 33000000,
            synopsis: 'Deckard hunts replicants in a dystopia.',
            banner_image: 'https://image.tmdb.org/t/p/original/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg',
            thumbnail_image: 'https://image.tmdb.org/t/p/w1280/63N9uy8nd9j7Eog2axPQ8lbr3Wj.jpg',
            video_link: 'https://www.youtube.com/embed/eogpIG53Cis'
          }
        ]
      },
      {
        "id": 4,
        "title": "Action",
        "movies": [
          {
            id: 8,
            title: 'The Dark Knight',
            year: 2008,
            genre: 'Action',
            description: "Batman faces the Joker in a battle for Gotham's soul.",
            director: 'Christopher Nolan',
            cast: ['John Doe', 'Jane Smith', 'Mike Lee'],
            runtime_minutes: 152,
            rating: 'PG-13',
            imdb_score: 9,
            budget_usd: 185000000,
            box_office_usd: 1004000000,
            synopsis: 'Batman battles the chaotic Joker.',
            banner_image: 'https://image.tmdb.org/t/p/original/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
            thumbnail_image: 'https://image.tmdb.org/t/p/w1280/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
            video_link: 'https://www.youtube.com/embed/EXeTwQWrcwY'
          },
          {
            id: 14,
            title: 'The Avengers',
            year: 2012,
            genre: 'Action',
            description: 'Superheroes team up to save Earth from invasion.',
            director: 'Joss Whedon',
            cast: ['John Doe', 'Jane Smith', 'Mike Lee'],
            runtime_minutes: 143,
            rating: 'PG-13',
            imdb_score: 8,
            budget_usd: 220000000,
            box_office_usd: 1519000000,
            synopsis: "Heroes unite against Loki's invasion.",
            banner_image: 'https://image.tmdb.org/t/p/original/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg',
            thumbnail_image: 'https://image.tmdb.org/t/p/w1280/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg',
            video_link: 'https://www.youtube.com/embed/eOrNdBpGMv8'
          },
          {
            id: 19,
            title: 'Gladiator',
            year: 2000,
            genre: 'Action',
            description: 'A Roman general seeks revenge as a gladiator.',
            director: 'Ridley Scott',
            cast: ['John Doe', 'Jane Smith', 'Mike Lee'],
            runtime_minutes: 155,
            rating: 'R',
            imdb_score: 8.5,
            budget_usd: 103000000,
            box_office_usd: 460000000,
            synopsis: 'Maximus seeks vengeance in the arena.',
            banner_image: 'https://image.tmdb.org/t/p/original/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg',
            thumbnail_image: 'https://image.tmdb.org/t/p/w1280/ty8TGRuvsywJFIvW6B2W7zkKJEe.jpg',
            video_link: 'https://www.youtube.com/embed/owK1qxDselE'
          },
          {
            id: 27,
            title: 'Mad Max: Fury Road',
            year: 2015,
            genre: 'Action',
            description: 'Survivors flee across a post-apocalyptic wasteland.',
            director: 'George Miller',
            cast: ['John Doe', 'Jane Smith', 'Mike Lee'],
            runtime_minutes: 120,
            rating: 'R',
            imdb_score: 8.1,
            budget_usd: 150000000,
            box_office_usd: 378000000,
            synopsis: "Max and Furiosa flee a tyrant's forces.",
            banner_image: 'https://image.tmdb.org/t/p/original/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg',
            thumbnail_image: 'https://image.tmdb.org/t/p/w1280/8tZYtuWezp8Jbcsvzey6ObaTbhV.jpg',
            video_link: 'https://www.youtube.com/embed/hEJnMQG9ev8'
          },
          {
            id: 33,
            title: 'Die Hard',
            year: 1988,
            genre: 'Action',
            description: 'A cop battles terrorists in a skyscraper.',
            director: 'John McTiernan',
            cast: ['John Doe', 'Jane Smith', 'Mike Lee'],
            runtime_minutes: 132,
            rating: 'R',
            imdb_score: 8.2,
            budget_usd: 28000000,
            box_office_usd: 140000000,
            synopsis: 'John McClane stops a terrorist takeover.',
            banner_image: 'https://image.tmdb.org/t/p/original/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg',
            thumbnail_image: 'https://image.tmdb.org/t/p/w1280/yFihWxQcmqHKCmH8avCaPYF8Qo.jpg',
            video_link: 'https://www.youtube.com/embed/jaJuwL0-zsI'
          }
        ]
      }
    ]
  }