export const data = {
    "movies_with_media": [
      {
        "id": 1,
        "title": "The Shawshank Redemption",
        "year": 1994,
        "genre": "Drama",
        "description": "Two imprisoned men bond over years, finding solace and redemption through acts of decency.",
        "director": "Frank Darabont",
        "cast": ["Tim Robbins", "Morgan Freeman"],
        "runtime_minutes": 142,
        "rating": "R",
        "imdb_score": 9.3,
        "budget_usd": 25000000,
        "box_office_usd": 58800000,
        "synopsis": "Andy Dufresne, wrongly convicted, plans his escape from prison.",
        "banner_image": "https://image.tmdb.org/t/p/original/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg",
        "thumbnail_image": "https://image.tmdb.org/t/p/w1280/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg",
        "video_link": "https://www.youtube.com/watch?v=6hB3S9bIaco"
      },
      {
        "id": 2,
        "title": "The Godfather",
        "year": 1972,
        "genre": "Crime",
        "description": "The aging patriarch of an organized crime dynasty transfers control to his reluctant son.",
        "director": "Francis Ford Coppola",
        "cast": ["Marlon Brando", "Al Pacino"],
        "runtime_minutes": 175,
        "rating": "R",
        "imdb_score": 9.2,
        "budget_usd": 6000000,
        "box_office_usd": 245000000,
        "synopsis": "Michael Corleone takes over the family mafia business.",
        "banner_image": "https://image.tmdb.org/t/p/original/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
        "thumbnail_image": "https://image.tmdb.org/t/p/w1280/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
        "video_link": "https://www.youtube.com/watch?v=sY1S34973zA"
      },
      {
        "id": 3,
        "title": "Inception",
        "year": 2010,
        "genre": "Sci-Fi",
        "description": "A thief with the ability to enter dreams is given a final job that could win him his freedom.",
        "director": "Christopher Nolan",
        "cast": ["Leonardo DiCaprio", "Joseph Gordon-Levitt"],
        "runtime_minutes": 148,
        "rating": "PG-13",
        "imdb_score": 8.8,
        "budget_usd": 160000000,
        "box_office_usd": 829000000,
        "synopsis": "Dom Cobb plants an idea in a dream within a dream.",
        "banner_image": "https://image.tmdb.org/t/p/original/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg",
        "thumbnail_image": "https://image.tmdb.org/t/p/w1280/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg",
        "video_link": "https://www.youtube.com/watch?v=YoHD9XEInc0"
      },
      {
        "id": 4,
        "title": "Pulp Fiction",
        "year": 1994,
        "genre": "Crime",
        "description": "Various interconnected stories of criminals, hitmen, and a mysterious briefcase.",
        "director": "Quentin Tarantino",
        "cast": ["John Travolta", "Samuel L. Jackson"],
        "runtime_minutes": 154,
        "rating": "R",
        "imdb_score": 8.9,
        "budget_usd": 8000000,
        "box_office_usd": 213000000,
        "synopsis": "Intertwined tales of violence and redemption.",
        "banner_image": "https://image.tmdb.org/t/p/original/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg",
        "thumbnail_image": "https://image.tmdb.org/t/p/w1280/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg",
        "video_link": "https://www.youtube.com/watch?v=s7EdQ4FqbhY"
      },
      {
        "id": 5,
        "title": "Fight Club",
        "year": 1999,
        "genre": "Drama",
        "description": "An insomniac forms an underground fight club.",
        "director": "David Fincher",
        "cast": ["Brad Pitt", "Edward Norton"],
        "runtime_minutes": 139,
        "rating": "R",
        "imdb_score": 8.8,
        "budget_usd": 63000000,
        "box_office_usd": 101000000,
        "synopsis": "A man creates chaos through an alter ego.",
        "banner_image": "https://image.tmdb.org/t/p/original/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg",
        "thumbnail_image": "https://image.tmdb.org/t/p/w1280/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg",
        "video_link": "https://www.youtube.com/watch?v=SUXWAEX2jlg"
      },
      {
        "id": 6,
        "title": "The Avengers",
        "year": 2012,
        "genre": "Action",
        "description": "Superheroes team up to save Earth from invasion.",
        "director": "Joss Whedon",
        "cast": ["Robert Downey Jr.", "Chris Evans"],
        "runtime_minutes": 143,
        "rating": "PG-13",
        "imdb_score": 8.0,
        "budget_usd": 220000000,
        "box_office_usd": 1519000000,
        "synopsis": "Heroes unite against Loki's invasion.",
        "banner_image": "https://image.tmdb.org/t/p/original/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg",
        "thumbnail_image": "https://image.tmdb.org/t/p/w1280/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg",
        "video_link": "https://www.youtube.com/watch?v=eOrNdBpGMv8"
      }
    ]
  }