export const SPLASH_SCREEN_REQUEST = 'SPLASH_SCREEN_REQUEST';
export const SPLASH_SCREEN_SUCCESS = 'SPLASH_SCREEN_SUCCESS';
export const SPLASH_SCREEN_FAILURE = 'SPLASH_SCREEN_FAILURE';

export const HOME_SCREEN_REQUEST = 'HOME_SCREEN_REQUEST';
export const HOME_SCREEN_SUCCESS = 'HOME_SCREEN_SUCCESS';
export const HOME_SCREEN_FAILURE = 'HOME_SCREEN_FAILURE';

export const DETAILED_SCREEN_REQUEST = 'FDETAILED_SCREEN_REQUEST';
export const DETAILED_SCREEN_SUCCESS = 'DETAILED_SCREEN_SUCCESS';
export const DETAILED_SCREEN_FAILURE = 'DETAILED_SCREEN_FAILURE';